CREATE DATABASE Emelyanenko_DB_Payment;

GO

USE Emelyanenko_DB_Payment;

CREATE TABLE [User]
(ID INT PRIMARY KEY IDENTITY(0, 1),
Login VARCHAR(MAX) NOT NULL,
Password VARCHAR(MAX) NOT NULL,
Role VARCHAR(50),
FIO VARCHAR(MAX),
Photo NVARCHAR(MAX));

CREATE TABLE Category
(ID INT PRIMARY KEY IDENTITY(0, 1),
Name VARCHAR(MAX));

CREATE TABLE Payment
(ID INT PRIMARY KEY IDENTITY(0, 1),
UserID INT NOT NULL REFERENCES [User],
CategoryID INT NOT NULL REFERENCES Category,
Date DATE NOT NULL,
Name NVARCHAR(50) NOT NULL,
Num DECIMAL(18, 0) NOT NULL,
Price DECIMAL(18, 0) NOT NULL);