//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _222_Emelyanenko
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Emelyanenko_DB_PaymentEntities2 : DbContext
    {
        public Emelyanenko_DB_PaymentEntities2()
            : base("name=Emelyanenko_DB_PaymentEntities2")
        {
        }

        private static Emelyanenko_DB_PaymentEntities2 instance;

        public static Emelyanenko_DB_PaymentEntities2 getInstance()
        {
            if (instance == null)
            {
                instance = new Emelyanenko_DB_PaymentEntities2();
            }
            return instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
